// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WPR.Data;

#nullable disable

namespace WPR.Migrations.Migrations
{
    [DbContext(typeof(WprDbContext))]
    [Migration("20220411152816_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WPR.Web.Data.Domains.Comments.DbModels.CommentDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateOnly>("CreatingDate")
                        .HasColumnType("date")
                        .HasColumnName("creating_date");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.HasKey("Id")
                        .HasName("pk_comment");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_comment_author_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_comment_project_id");

                    b.ToTable("comment", (string)null);
                });

            modelBuilder.Entity("WPR.Web.Data.Domains.Links.DbModels.LinkDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_link");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_link_project_id");

                    b.ToTable("link", (string)null);
                });

            modelBuilder.Entity("WPR.Web.Data.Domains.Projects.DbModels.ProjectDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.HasKey("Id")
                        .HasName("pk_project");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_project_author_id");

                    b.ToTable("project", (string)null);
                });

            modelBuilder.Entity("WPR.Web.Data.Domains.Users.DbModels.UserDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tag");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasAlternateKey("Tag")
                        .HasName("ak_user_tag");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("WPR.Web.Data.Domains.Comments.DbModels.CommentDbModel", b =>
                {
                    b.HasOne("WPR.Web.Data.Domains.Users.DbModels.UserDbModel", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comment_users_user_db_model_id");

                    b.HasOne("WPR.Web.Data.Domains.Projects.DbModels.ProjectDbModel", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comment_projects_project_db_model_id");
                });

            modelBuilder.Entity("WPR.Web.Data.Domains.Links.DbModels.LinkDbModel", b =>
                {
                    b.HasOne("WPR.Web.Data.Domains.Projects.DbModels.ProjectDbModel", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_link_projects_project_db_model_id");
                });

            modelBuilder.Entity("WPR.Web.Data.Domains.Projects.DbModels.ProjectDbModel", b =>
                {
                    b.HasOne("WPR.Web.Data.Domains.Users.DbModels.UserDbModel", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_users_user_db_model_id");
                });
#pragma warning restore 612, 618
        }
    }
}
